title: Python bytes - Walgelijke gerechten
hero_image: images/banner.png
description: Maak je eigen walgelijke recept met behulp van print-statements en emoji's in Python!
meta_title: Leer programmeren met Walgelijke gerechten | Raspberry Pi Foundation
meta_description: Leer Python met de Raspberry Pi Foundation. Programmeer een receptkaart die heerlijk walgelijk is!
version: 1
listed: true
copyedit: false
last_tested: "2025-04-14"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
    completion:
      - internal
      - external
