title: "Picnic Panic 🧺😲🥪"
hero_image: images/banner.png
description: Write a short, silly story using Python print statements and emoji.
meta_title: Python coding projects for kids and teens | Picnic Panic
meta_description: Learn Python with the Raspberry Pi Foundation. Use print statements to write a funny picnic story full of sandwiches, surprises and emoji.
version: 1
listed: false
copyedit: false
last_tested: "2025-04-04"
steps:
  - title: step 1
  - title: step 2
    completion:
      - engaged
  - title: step 3
  - title: step 4
  - title: step 5
    completion:
      - internal
      - external
